version: '3.5'

services:
  main_service:
    build: .
    #restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}
    env_file:
      - ./config/${ENVIRONMENT:-dev}/variables.env
    volumes:
      - ./volumes/data:/data
      - ./volumes/log:/log
      - ./config/${ENVIRONMENT:-dev}/cron.d:/etc/cron.d
